export const negativePrompt = [
  "watermark",
  "signature",
  "accidental letters",
  "missing typography",
  "missing Soul of Love branding",
  "missing energy score",
  "missing aura panel",
  "missing card name",
  "missing universe message panel",
  "unreadable Thai text",
  "unreadable English text",
  "malformed glyphs",
  "upside-down characters",
  "rotated human figure",
  "inverted portrait",
  "horror",
  "gore",
  "demons",
  "fear-based fortune telling",
  "scary expression",
  "aggressive fantasy armor",
  "RPG splash art",
  "oversexualized costume",
  "distorted hands",
  "malformed anatomy",
  "extra fingers",
  "broken scales",
  "cluttered sacred geometry",
  "cluttered poster layout",
  "busy background",
  "harsh neon",
  "cheap yellow gold",
  "heavy tarot border",
  "low resolution",
  "blurry subject",
  "fake watermark"
];

export function buildNegativePrompt() {
  return negativePrompt.join(", ");
}
